# Generated by Django 5.1.4 on 2025-06-15 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70)),
                ('roll', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('year', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('start_dest', models.CharField(max_length=50)),
                ('end_dest', models.CharField(max_length=30)),
            ],
        ),
    ]
