# Generated by Django 5.1.4 on 2025-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='period',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concession',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
