# Generated by Django 5.1.4 on 2025-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
